# Generated by Django 6.0.3 on 2026-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0003_badge_alter_perfil_usuario_perfil_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icone',
        ),
        migrations.AddField(
            model_name='badge',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
