# Generated by Django 6.0.3 on 2026-03-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0008_perfil_ofensiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
